---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nglohitech/public_html/fleetngv2
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -R app bootstrap config database docs Modules public resources routes scripts tests vendor artisan composer.json composer.lock package.json package-lock.json "$DEPLOYPATH"/
    - /bin/cp -R .env.example "$DEPLOYPATH"/
    - cd "$DEPLOYPATH" && php artisan migrate --force
    - cd "$DEPLOYPATH" && php artisan optimize:clear
    - cd "$DEPLOYPATH" && php artisan config:clear
    - cd "$DEPLOYPATH" && php artisan route:clear
    - cd "$DEPLOYPATH" && php artisan view:clear
    - cd "$DEPLOYPATH" && php artisan cache:clear
