const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');

async function main() {
  const browser = await chromium.launch({ headless:true, channel:'chrome' });
  const page = await browser.newPage({ viewport:{ width:1440,height:1050 } });
  const errors = [], businessRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', req => { if (/\/api\/|flutterwave|firebase|twilio/.test(req.url())) businessRequests.push(req.url()); });
  const base = process.env.CUSTOMER_PREVIEW_URL || 'http://127.0.0.1:8021/customer-preview/';
  const screenshot = name => page.screenshot({ path:path.join(os.tmpdir(),'fleetng-customer-' + name + '.png'), fullPage:true });
  const waitHeading = title => page.getByRole('heading', { name:title, exact:true }).waitFor();
  try {
    await page.goto(base);
    await waitHeading('Good day, Alex');
    assert.equal(await page.locator('.brand img').evaluate(img => img.complete && img.naturalWidth > 0),true);
    await screenshot('desktop');
    await page.getByRole('link',{name:'My trips',exact:true}).click();
    await waitHeading('My trips');
    assert.equal(await page.locator('tbody tr').count(),5);
    await page.getByRole('button',{name:'next page',exact:true}).click();
    assert.equal(await page.locator('tbody tr').count(),4);
    await page.getByRole('button',{name:'first page',exact:true}).click();
    await page.getByRole('textbox',{name:'Search trips'}).fill('no-matching-trip');
    await page.getByRole('heading',{name:'No matching trips'}).waitFor();
    await page.getByRole('textbox',{name:'Search trips'}).fill('');
    await page.getByRole('tab',{name:'Completed',exact:true}).click();
    assert.equal(await page.locator('tbody tr').count(),4);
    await page.getByRole('tab',{name:'All',exact:true}).click();
    await page.getByRole('checkbox',{name:'Select trip 2401',exact:true}).check();
    await page.getByRole('button',{name:'Pay selected',exact:true}).click();
    await page.getByRole('button',{name:'Simulate successful payment',exact:true}).click();
    await page.getByRole('checkbox',{name:'Select trip 2401',exact:true}).waitFor();
    assert.equal(await page.getByRole('checkbox',{name:'Select trip 2401',exact:true}).isDisabled(),true);
    await page.getByRole('link',{name:'Book a trip',exact:true}).click();
    await page.getByLabel('Pickup location',{exact:true}).selectOption('2');
    await page.getByLabel('Drop-off location',{exact:true}).fill('Demo acceptance delivery site');
    await page.getByLabel('Proposed trip cost (NGN)',{exact:true}).fill('125000');
    assert.equal(await page.locator('.booking-summary .total strong').innerText(),'NGN 125,000');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('Merchant',{exact:true}).selectOption('21');
    await page.getByRole('radio',{name:'Demo Driver A DEMO-101'}).check();
    await page.getByRole('button',{name:'Save draft',exact:true}).click();
    await waitHeading('Draft bookings');
    await page.getByRole('link',{name:'Edit draft 902',exact:true}).click();
    await waitHeading('Finish your booking');
    assert.equal(await page.getByLabel('Drop-off location',{exact:true}).inputValue(),'Demo acceptance delivery site');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByRole('button',{name:'Confirm demo booking',exact:true}).click();
    await waitHeading('Trip #2410');
    assert.equal(await page.getByText('Demo acceptance delivery site',{exact:true}).count(),1);
    await screenshot('booking');
    await page.getByRole('button',{name:'Change assignment',exact:true}).click();
    await page.getByLabel('Merchant / driver',{exact:true}).selectOption('103');
    await page.getByRole('button',{name:'Save assignment',exact:true}).click();
    await page.getByText('Demo Driver C',{exact:true}).waitFor();
    await page.reload();
    await waitHeading('Trip #2410');
    await page.getByText('Demo Driver C',{exact:true}).waitFor();
    await page.getByRole('link',{name:'My account',exact:true}).click();
    await page.getByLabel('First name',{exact:true}).fill('Taylor');
    await page.getByRole('button',{name:'Save changes',exact:true}).click();
    await page.getByRole('heading',{name:'Taylor Morgan',exact:true}).waitFor();
    await page.getByRole('button',{name:'Sign out',exact:true}).click();
    await page.getByRole('button',{name:'Open demo account',exact:true}).waitFor();
    await page.getByRole('button',{name:'Open demo account',exact:true}).click();
    await page.getByLabel('Verification code',{exact:true}).fill('999999');
    await page.getByRole('button',{name:'Verify and continue',exact:true}).click();
    await page.getByText('Incorrect code. The development code is 123456.',{exact:true}).waitFor();
    await page.getByLabel('Verification code',{exact:true}).fill('123456');
    await page.getByRole('button',{name:'Verify and continue',exact:true}).click();
    await waitHeading('Good day, Taylor');
    await page.getByRole('button',{name:'Reset sample data',exact:true}).click();
    await page.getByRole('button',{name:'Reset demo',exact:true}).click();
    await waitHeading('Good day, Alex');
    for (const width of [320,390,768]) {
      await page.setViewportSize({width,height:844});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'No page overflow at ' + width);
      await screenshot('mobile-' + width);
      await page.getByRole('button',{name:'Open navigation',exact:true}).click();
      await page.getByRole('link',{name:'My trips',exact:true}).click();
      await waitHeading('My trips');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'Table contained at ' + width);
      await screenshot('table-' + width);
      await page.getByRole('link',{name:'Book a trip',exact:true}).click();
      await waitHeading('Book a trip');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'Booking contained at ' + width);
      await screenshot('form-' + width);
      await page.goto(base + '#/overview');
      await waitHeading('Good day, Alex');
    }
    await page.setViewportSize({width:1440,height:1050});
    await page.getByRole('button',{name:'Sign out',exact:true}).click();
    await page.getByRole('tab',{name:'New customer',exact:true}).click();
    await page.getByLabel('First name',{exact:true}).fill('New');
    await page.getByLabel('Last name',{exact:true}).fill('Customer');
    await page.getByLabel('Email address',{exact:true}).fill('new@example.com');
    await page.getByLabel('Phone number',{exact:true}).fill('8000000001');
    await page.getByRole('button',{name:'Create demo account',exact:true}).click();
    await page.getByLabel('Verification code',{exact:true}).fill('123456');
    await page.getByRole('button',{name:'Verify and continue',exact:true}).click();
    await waitHeading('Good day, New');
    assert.equal(await page.locator('tbody tr').count(),0,'New account must not inherit another account\'s trips');
    await page.getByRole('heading',{name:'No trips yet',exact:true}).waitFor();
    assert.deepEqual(errors,[],'No uncaught browser errors');
    assert.deepEqual(businessRequests,[],'Preview must never contact business APIs');
    console.log('PASS: desktop/mobile rendering, assets, search, filters, pagination, payment simulation, draft save/edit/confirm, driver assignment, reload persistence, profile, login/logout, reset, and zero business requests.');
    console.log('Screenshots: ' + path.join(os.tmpdir(),'fleetng-customer-*.png'));
  } catch (error) {
    console.error('Browser errors:',errors);
    console.error('Page content:',(await page.locator('body').innerText()).slice(0,2200));
    await screenshot('failure');
    throw error;
  } finally { await browser.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
